### ISSUE TITLE
Automate {KOSS}Hub setup

### ISSUE THREAD

**Issue by proffapt** [sheharyaar/ptokax#8]
### POA
- [x] To create a systemd script which does the following job:
  - [x] The `.py` script - runs everytime on booting
    - [x] Detects if the pi has access to internet on boot-up or not.
    - [x] If yes -> do nothing. If no -> delete the lines for static ip configuration in `dhcpcd.conf`.
    - [x] starts the setup script, which configures current ip as static and starts ptokax service if not already.
  - [x] The `.sh` script - install dependencies and executes the `.py` script.
- [x] Configure aliases instead of abstract path. 
- [x] New `ptokax-setup.sh` for new needs
  - [x] Automate the argument requirements for the setup-script.
  - [x] Fix the bug - if it's not handled already - [BUG](https://github.com/sheharyaar/ptokax#bug-fix-ban-followed-by-wrong-redirection)
  - [x] Check for every task if they are handled before or not

### Testing w/o LED
  - [x] ptokax-alias
  - [x] ptokax-config.sh
  - [x] ptokax-stop.sh
  - [x] ./ptokax-start.sh
  - [x] ./ptokax-setup.sh
  - [ ] systemd 
    - [x] ptokax.service
    - [x]  ptokax-startup-service.sh
    - [ ] ptokax-network-check.py
      - [ ] Network Access Check
      - [x] ptokax-setup.sh
- [x] Improve script outputs from in script commands based on test runs.
- [x] Check the `-ne $pid` part.. in `ipofpi.sh` & `ptokax-setup.sh`  and one more.. if they work or not..
- [x] `setsid` if it is available or not

# LED
The goal is to..
Output logs into LED display with main focus on IP of PI- https://pypi.org/project/RPi.GPIO/.
For now it's POA has not been decided, but surely be done after w/o LED is deployment ready.

### Why?
To make it plug and play job to setup DC++.

**Comment by sheharyaar** [comment]
For this : 
- use ioctl calls in python using `SIOCGIFCONF` and other ioctl calls.
- use sed in python (either using a library or just exec) to comment out/in the dhcpcd.conf
- after getting the information, use this to integrate with RPI.GPIO python library to display at the LED Screen.
- use exec to run the setup script for ptokax

Also:
- this would require to remove manual input of installing ptokax and automate that scsript further

**Comment by sheharyaar** [comment]
https://man7.org/linux/man-pages/man7/netdevice.7.html

**Comment by sheharyaar** [comment]
https://github.com/sheharyaar/ptokax/pull/10

Work in progress

**Comment by sheharyaar** [comment]
I have ordered the LED Matrix display 64x64. Will be delivered by next week. Will complete this and test this next week

**Comment by proffapt** [comment]
> I have ordered the LED Matrix display 64x64. Will be delivered by next week. Will complete this and test this next week

Noice, will start some reading and maybe some work by today.. as I might have some time if my health allows :)

**Comment by proffapt** [comment]
> this would require to remove manual input of installing ptokax and automate that scsript further

what does this mean?
Are you referring to options we get while setting up ptokax in the setup script?

**Comment by sheharyaar** [comment]
Yes those options

**Comment by proffapt** [comment]
Initial TODO list done.

New tasks:
- [ ] Automate the argument requirements for the setup.
- [ ] Don't know when to run setup script exactly.
- [ ] Improve script outputs from in script commands based on test runs.
- [ ] Check the `-ne $pid` part.. in `ipofpi.sh` & `ptokax-setup.sh`  and one more.. if they work or not..

**Comment by sheharyaar** [comment]
> Check the -ne $pid part.. in ipofpi.sh & ptokax-setup.sh and one more.. if they work or not..
For this you can use pgrep too

**Comment by proffapt** [comment]
> > Check the -ne $pid part.. in ipofpi.sh & ptokax-setup.sh and one more.. if they work or not..
> 
> For this you can use pgrep too

I remember I tried pgrep but it didn't work for some reason ¯\_(ツ)_/¯

**Comment by sheharyaar** [comment]
pgrep with `-x` flag?

**Comment by proffapt** [comment]
> pgrep with `-x` flag?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/86282911/212462313-b8ed9ce0-b28c-4f94-b7ad-8addb5da9e11.png">

tho changed the logic.. idk why i put -ne instead of -eq.. checked.. works fine

**Comment by sheharyaar** [comment]
pgrep mein name dalna hoga process ka

**Comment by sheharyaar** [comment]
Eg : `pgrep -x Xorg`

**Comment by proffapt** [comment]
> Eg : `pgrep -x Xorg`

The way I wanted the spinner function to be, I can't use name hence no pgrep; I wanted to use pid only and have tested successfully.. it works!

**Comment by proffapt** [comment]
Closing this issue, as it makes no sense in tracking the same thing's progress and POA in an issue and a WIP PR.
